apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aydo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aydo
    app.kubernetes.io/part-of: byoc-app-qaas
  name: aydo
spec:
  rules:
  - host: aydo-byoc-xzju-tenant.apps.4cd0cad7d4104e0899aa.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: aydo
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
